### ISSUE TITLE
manual input is unreadable in dark mode

### ISSUE THREAD

**Issue by jessetan** [cositehq/sanity-plugin-simpler-color-input#1]
Studio in light mode:
![Screenshot 2023-10-09 at 16 44 03](https://github.com/cositehq/sanity-plugin-simpler-color-input/assets/3284111/dc8d7549-e869-495d-8065-1effa9f988d0)

Studio in dark mode:
![Screenshot 2023-10-09 at 16 44 13](https://github.com/cositehq/sanity-plugin-simpler-color-input/assets/3284111/b7dc0396-0085-4059-a903-b97eb23138c9)

**Comment by AlyssaKirstine** [comment]
Fixed in [v1.2.1](https://github.com/cositehq/sanity-plugin-simpler-color-input/releases/tag/v1.2.1) :)
