### ISSUE TITLE
"TypeError: Cannot redefine property: render" when starting studio

### ISSUE THREAD

**Issue by jessetan** [cositehq/sanity-plugin-simpler-color-input#4]
Version 2.x switched the color picker dependency from `react-color` to `@uiw/react-color` in [this commit](https://github.com/cositehq/sanity-plugin-simpler-color-input/commit/d3731d3c92cd7d0d257611d7c8789040c6addd16).
Ever since then, Studio no longer starts for me, but gives the error `TypeError: Cannot redefine property: render`

This is a reported issue in `@uiw/react-color`: https://github.com/uiwjs/react-color/issues/104
There are some workarounds in that thread.

**Comment by AlyssaKirstine** [comment]
Hi @jessetan thanks for flagging this. I'll hopefully have a chance to take a look into it soon.

**Comment by AlyssaKirstine** [comment]
@jessetan This was fixed in v2.2.0! Thanks for flagging and thanks to @theostrahlen for fixing it.

**Comment by AlyssaKirstine** [comment]
cc @tegansnyder since I noticed you made a fork trying to fix this same issue.
